# Generated by Django 3.0.4 on 2020-04-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banasadmin', '0002_auto_20200415_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='task',
            field=models.CharField(default='pending', max_length=100),
            preserve_default=False,
        ),
    ]
