# Generated by Django 3.0.4 on 2020-04-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banasadmin', '0005_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
