# Generated by Django 3.0.4 on 2020-04-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banasadmin', '0006_remove_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
