# Generated by Django 3.0.8 on 2020-08-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banasadmin', '0012_remove_dailyentry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='route',
        ),
    ]
